# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RTB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tRTB.proto\"\x88\x01\n\nBidRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x03imp\x18\x02 \x03(\x0b\x32\x0b.Impression\x12\x13\n\x04user\x18\x03 \x01(\x0b\x32\x05.User\x12\x17\n\x06\x64\x65vice\x18\x04 \x01(\x0b\x32\x07.Device\x12\x13\n\x04site\x18\x05 \x01(\x0b\x32\x05.Site\x12\x11\n\x03\x61pp\x18\x06 \x01(\x0b\x32\x04.App\"Z\n\nImpression\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x06\x62\x61nner\x18\x02 \x01(\x0b\x32\x07.Banner\x12\x15\n\x05video\x18\x03 \x01(\x0b\x32\x06.Video\x12\x10\n\x08\x62idfloor\x18\x04 \x01(\x02\"-\n\x06\x42\x61nner\x12\t\n\x01w\x18\x01 \x03(\x05\x12\t\n\x01h\x18\x02 \x03(\x05\x12\r\n\x05mimes\x18\x03 \x03(\t\"@\n\x05Video\x12\r\n\x05mimes\x18\x01 \x03(\t\x12\x13\n\x0bminduration\x18\x02 \x01(\x05\x12\x13\n\x0bmaxduration\x18\x03 \x01(\x05\"7\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyeruid\x18\x02 \x01(\t\x12\x11\n\x03geo\x18\x03 \x01(\x0b\x32\x04.Geo\"3\n\x06\x44\x65vice\x12\n\n\x02ip\x18\x01 \x01(\t\x12\n\n\x02ua\x18\x02 \x01(\t\x12\x11\n\x03geo\x18\x03 \x01(\x0b\x32\x04.Geo\">\n\x03Geo\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\"\"\n\x04Site\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"!\n\x03\x41pp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x62undle\x18\x02 \x01(\t\"F\n\x0b\x42idResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x07seatbid\x18\x02 \x03(\x0b\x32\x08.SeatBid\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"*\n\x07SeatBid\x12\x11\n\x03\x62id\x18\x01 \x03(\x0b\x32\x04.Bid\x12\x0c\n\x04seat\x18\x02 \x01(\t\"X\n\x03\x42id\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05impid\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0c\n\x04\x61\x64id\x18\x04 \x01(\t\x12\x0b\n\x03\x61\x64m\x18\x05 \x01(\t\x12\x0c\n\x04nurl\x18\x06 \x01(\tb\x06proto3')



_BIDREQUEST = DESCRIPTOR.message_types_by_name['BidRequest']
_IMPRESSION = DESCRIPTOR.message_types_by_name['Impression']
_BANNER = DESCRIPTOR.message_types_by_name['Banner']
_VIDEO = DESCRIPTOR.message_types_by_name['Video']
_USER = DESCRIPTOR.message_types_by_name['User']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
_GEO = DESCRIPTOR.message_types_by_name['Geo']
_SITE = DESCRIPTOR.message_types_by_name['Site']
_APP = DESCRIPTOR.message_types_by_name['App']
_BIDRESPONSE = DESCRIPTOR.message_types_by_name['BidResponse']
_SEATBID = DESCRIPTOR.message_types_by_name['SeatBid']
_BID = DESCRIPTOR.message_types_by_name['Bid']
BidRequest = _reflection.GeneratedProtocolMessageType('BidRequest', (_message.Message,), {
  'DESCRIPTOR' : _BIDREQUEST,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:BidRequest)
  })
_sym_db.RegisterMessage(BidRequest)

Impression = _reflection.GeneratedProtocolMessageType('Impression', (_message.Message,), {
  'DESCRIPTOR' : _IMPRESSION,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Impression)
  })
_sym_db.RegisterMessage(Impression)

Banner = _reflection.GeneratedProtocolMessageType('Banner', (_message.Message,), {
  'DESCRIPTOR' : _BANNER,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Banner)
  })
_sym_db.RegisterMessage(Banner)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Video)
  })
_sym_db.RegisterMessage(Video)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  })
_sym_db.RegisterMessage(Device)

Geo = _reflection.GeneratedProtocolMessageType('Geo', (_message.Message,), {
  'DESCRIPTOR' : _GEO,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Geo)
  })
_sym_db.RegisterMessage(Geo)

Site = _reflection.GeneratedProtocolMessageType('Site', (_message.Message,), {
  'DESCRIPTOR' : _SITE,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Site)
  })
_sym_db.RegisterMessage(Site)

App = _reflection.GeneratedProtocolMessageType('App', (_message.Message,), {
  'DESCRIPTOR' : _APP,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:App)
  })
_sym_db.RegisterMessage(App)

BidResponse = _reflection.GeneratedProtocolMessageType('BidResponse', (_message.Message,), {
  'DESCRIPTOR' : _BIDRESPONSE,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:BidResponse)
  })
_sym_db.RegisterMessage(BidResponse)

SeatBid = _reflection.GeneratedProtocolMessageType('SeatBid', (_message.Message,), {
  'DESCRIPTOR' : _SEATBID,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:SeatBid)
  })
_sym_db.RegisterMessage(SeatBid)

Bid = _reflection.GeneratedProtocolMessageType('Bid', (_message.Message,), {
  'DESCRIPTOR' : _BID,
  '__module__' : 'RTB_pb2'
  # @@protoc_insertion_point(class_scope:Bid)
  })
_sym_db.RegisterMessage(Bid)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BIDREQUEST._serialized_start=14
  _BIDREQUEST._serialized_end=150
  _IMPRESSION._serialized_start=152
  _IMPRESSION._serialized_end=242
  _BANNER._serialized_start=244
  _BANNER._serialized_end=289
  _VIDEO._serialized_start=291
  _VIDEO._serialized_end=355
  _USER._serialized_start=357
  _USER._serialized_end=412
  _DEVICE._serialized_start=414
  _DEVICE._serialized_end=465
  _GEO._serialized_start=467
  _GEO._serialized_end=529
  _SITE._serialized_start=531
  _SITE._serialized_end=565
  _APP._serialized_start=567
  _APP._serialized_end=600
  _BIDRESPONSE._serialized_start=602
  _BIDRESPONSE._serialized_end=672
  _SEATBID._serialized_start=674
  _SEATBID._serialized_end=716
  _BID._serialized_start=718
  _BID._serialized_end=806
# @@protoc_insertion_point(module_scope)
